server: 
  port: 8081

spring: 
  activemq:
    broker-url: tcp://192.168.47.129:61616 #MQ服務器地址
    user: admin
    password: admin
  
  jms: 
    pub-sub-domain: false # false = Queue(默認)，true = Topic


